# Generated by Django 2.2.8 on 2019-12-30 16:46

from django.db import migrations


from members.models import Department


def department_add_slug(_apps, _schema_editor):
    for department in Department.objects.all():
        department.save()


def department_remove_slug(_apps, _schema_editor):
    for department in Department.objects.all():
        department.slug = "temp"
        department.save()


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0017_auto_20200124_1139"),
    ]

    operations = [
        migrations.RunPython(department_add_slug, department_remove_slug),
    ]
